### ISSUE TITLE
Private range

### ISSUE THREAD

**Issue by CMCDragonkai** [multiformats/py-multicodec#10]
With https://github.com/multiformats/multicodec/pull/191 merged, it is now possible to use private ranges with multicodec.

Can this library support private ranges?

I think this would mean being able to register additional custom types which will be allocated into the private range. And then being able to add the multicodec for the private keys.

**Comment by CMCDragonkai** [comment]
So I've just gone through `py-cid` and `py-multicodec`.

I can see that it's not possible to make use of any custom codecs. The functions `multicodec.add_prefix` and `multicodec.is_codec` is being used to check if my codec is legitimate.

I suggest that `py-multicodec` is given the feature to update the constants table at runtime, so it's possible for users to add their own entries to the tables in `constants.py`, or even merge with the `constants.py`.

This would enable this library to take advantage of the private range, and even use py-multicodec or more.

@dhruvbaldawa

**Comment by dhruvbaldawa** [comment]
Hi @CMCDragonkai,

I have taken the first stab at this problem here: https://github.com/multiformats/py-multicodec/pull/12
I feel that we can make this change without breaking the backward compatibility, while being extensible, let me know what you think of it.

**Comment by CMCDragonkai** [comment]
Did you see my MR #11?

**Comment by CMCDragonkai** [comment]
I had to turn multicodec into an object so I could register my private codec to it.

**Comment by rvagg** [comment]
closing from inactivity, archiving repository
