### ISSUE TITLE
Requirements are too specific

### ISSUE THREAD

**Issue by skorokithakis** [multiformats/py-multicodec#2]
Your requirements are too specific for a library, and they've broken my dependency resolution. You require `six==1.10.0`, for example, which is way too restrictive for a library. Another one of my dependencies made the similar mistake of mandating `six==1.11.0`, so now I have to choose if i want to use your projects or that one.

You should be using `>=` instead, or at least `>=1.10.0,<2.0.0`.

**Comment by dhruvbaldawa** [comment]
#3 resolves this issue, thanks for pointing it out.. changed this in all python multiformats repo

**Comment by skorokithakis** [comment]
Fantastic, thank you!
