### ISSUE TITLE
Multibase encodings incorrect.

### ISSUE THREAD

**Issue by Stebalien** [multiformats/py-multicodec#4]
Copied from https://github.com/multiformats/js-multicodec/issues/29

Multibase is concerned with symbols, not byte values. That is, the symbol 'f' mean hexadecimal, regardless of the underlying byte/bit sequence (if any) that happens to encode this symbol. For example, 'f' is still the hex multibase prefix even when written on paper.

base1, base2, base8, and base10 are for text. That is, 011010100 is multibase-encoded base2.

So, it's probably best to just remove these from this table (as this table is otherwise concerned with byte sequences).

**Comment by Stebalien** [comment]
Reported here: https://github.com/multiformats/multicodec/issues/76#issuecomment-439148212

**Comment by filips123** [comment]
@Stebalien I created #6 which adds support for auto-updating the table (like in `js-multicodec`), removes all `baseX` codecs and adds support for some new codecs that weren't supported yet (including ZeroNet).
